services:
  gamecubby-db:
    container_name: gamecubby-db
    image: postgres:17
    restart: always
    env_file: [.env]
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: ["8001:5432"]
    volumes:
      - gamecubby_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  gamecubby-api:
    container_name: gamecubby-api
    build:
      context: .
      dockerfile: gamecubby_api/Dockerfile
    image: rootifera/gamecubby-api:prod
    restart: unless-stopped
    env_file: [.env]
    depends_on:
      gamecubby-db:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes:
      - ./storage:/app/storage

  gamecubby-web:
    container_name: gamecubby-web
    image: rootifera/gamecubby-web:prod
    restart: unless-stopped
    depends_on:
      gamecubby-api:
        condition: service_started
    env_file: [.env]
    ports: ["3000:3000"]
    volumes:
      - ./storage:/storage

volumes:
  gamecubby_db_data:
