"""Add rating and updated_at to games

Revision ID: eb0b1283af7c
Revises: 7fae4af653cd
Create Date: 2025-07-22 20:42:44.331517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0b1283af7c'
down_revision: Union[str, Sequence[str], None] = '7fae4af653cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('updated_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'updated_at')
    op.drop_column('games', 'rating')
    # ### end Alembic commands ###
