name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: gamecubby
          POSTGRES_PASSWORD: gamecubby
          POSTGRES_DB: gamecubby
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://gamecubby:gamecubby@localhost:5432/gamecubby
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for database..."
            sleep 1
          done

      - name: Run Alembic migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest tests/
